services:
  app:
    container_name: python_app
    build:
      context: .
      dockerfile: containers/python/Dockerfile
    volumes:
      - ./application:/application
    # tty: true
    env_file:
      - .env
